### PR TITLE
Bug fixes in weight graph, create_workout, end_workout, add_exercise, add_set commands

### LINKED ISSUE #129: Fix the weight graph to not display multiple records from single day
The current weight graph displays different weight entries for a single day as different points on the graph. We want to fix this so that it only shows one datapoint per day.

### LINKED ISSUE #130: Fix add workout bugs that allowed user to get away with invalid inputs
Fix add workout bugs that allowed the user to get away with invalid inputs, such as

/create_workout

/create_workout n

/create_workout n/

/create_workout n/  d/20/10/25 t/1900

/create_workout n/d/20/10/25 t/1900

/create_workout n/PushDay d/20/10/25t/1900

### LINKED ISSUE #131: Fix bug related to 2 workouts to be existing simultaneously
Current version allows the user to create a new workout even though a workout exists and has not been ended. This needs to be fixed.

### LINKED ISSUE #132: Fix bugs related to addExercise() and addSet()
Add appropriate exceptions
Rework the logic to not accept invalid inputs

### PR DESCRIPTION
**Pull request by nitin19011**
Fixes #129
Fixes #130
Fixes #131
Fixes #132

### CODE REVIEW

File: src/main/java/seedu/fitchasers/WorkoutManager.java [hunk 1]
```diff
@@ -28,69 +29,154 @@ public void setWorkouts(ArrayList<Workout> workouts) {
...
     /**
      * Creates and adds a new workout to the list.
-     *
+     * <p>
      * Expected format: /create_workout n/NAME d/DD/MM/YY t/HHmm
      *
      * @param command the full user command containing workout details
      */
     public void addWorkout(String command) {
+        assert workouts != null : "workouts list should be initialized";
```
Comment (Kart04) [inline src/main/java/seedu/fitchasers/WorkoutManager.java]: The use of assert statements here is appropriate for internal consistency checks and documenting assumptions during development.

File: src/main/java/seedu/fitchasers/WorkoutManager.java [hunk 2]
```diff
@@ -28,69 +29,154 @@ public void setWorkouts(ArrayList<Workout> workouts) {
...
+            if (token.length > 0) {
+                dateStr = token[0];
+            }
         }
 
         String timeStr = "";
-        if (command.contains("t/")) {
-            String[] timeTokens = extractAfter(command, "t/").split("\\s+");
-            timeStr = timeTokens[0].trim();
+        if (tIdx != -1) {
```
Comment (Kart04) [inline src/main/java/seedu/fitchasers/WorkoutManager.java]: this pattern promotes clear, user-friendly validation and robust date/time parsing using the modern Java Time API as per best practices.
