### PR TITLE
Bug fixes to user input handling for logging of weight and creating a workout

### LINKED ISSUE #161: Check input date and time for workout creation
When the date or time entered is for the future, ask if the user is sure about proceeding with the future dates

### LINKED ISSUE #162: Check for invalid weight entries
Add validation to prevent users from entering future dates when logging weight.
If the user doesn’t provide a date, prompt them if they would like to use the current date instead.

### LINKED ISSUE #163: Give user the option to view weight as log or graph
Improve the view weight feature to allow the user to view the weight as a log or a graph.
Save the weight during the run and not only during exit.

### PR DESCRIPTION
**Pull request by nitin19011**
- Added check for missing date → prompts to use today’s date.
- Added duplicate date detection → asks if user wants to overwrite existing record.
- Fixed parsing bug when d/ is missing (handles /add_weight w/32 correctly).
- Added validation to prevent users from entering future dates when logging weight.
- If the user doesn’t provide a date, prompt them to use the current date instead.
-Improved the view weight feature to allow the user to view the weight as a log or a graph.
- Save the weight during the run and not only during exit.

Fixes #161 
Fixes #162
Fixes #163

### CODE REVIEW

File: src/main/java/seedu/fitchasers/FitChasers.java [hunk 1]
```diff
@@ -52,7 +52,7 @@ public static void main(String[] args) throws IOException {
                 userName = ui.enterName();
             }
             person = new Person(userName.trim());
-            ui.showMessage("Nice to meet you, " + person.getName() + "! Let's get started.");
+            ui.showMessage("Nice to meet you, " + person.getName() + "! Let's get started.\n");
```
Comment (Kart04) [inline src/main/java/seedu/fitchasers/FitChasers.java]: LGTM

File: src/main/java/seedu/fitchasers/WeightManager.java [hunk 2]
```diff
@@ -37,8 +64,40 @@ public void addWeight(String command) {
             double weightValue = Double.parseDouble(weightString);
             LocalDate entryDate = LocalDate.parse(dateString, DATE_FORMAT);
 
+            // Check if date is in the future
```
Comment (Kart04) [inline src/main/java/seedu/fitchasers/WeightManager.java]: Good idea of checking if the date is from the future.

**Review by Kart04 — APPROVED** [review]
